#
# Author: github.com/luncliff (luncliff@gmail.com)
#
# Experimental build for Bazel Build System
#   https://www.bazel.build/
#

jobs:
- job: BazelMacOS
  pool:
    vmImage: 'macOS-latest'
  steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          brew install bazel;
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          bazel build coroutine_portable;
          bazel build coroutine_concrt;
          bazel build coroutine_test_suite;
