#
# Author: github.com/luncliff (luncliff@gmail.com)
#
# References
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#passing-parameters
#

jobs:
- job: VS${{ parameters.visualstudio }}Clang
  pool:
    vmImage: 'vs2017-win2016'
  steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: git submodule update --init --recursive;
    - task: ChocolateyCommand@0
      inputs:
        command: 'install'
        installPackageId: 'ninja'
        installInstallArgs: '--no-progress --yes'
    - task: ChocolateyCommand@0
      inputs:
        command: 'install'
        installPackageId: 'llvm'
        installInstallArgs: '--no-progress --yes'
    - task: BatchScript@1
      inputs:
        filename: './scripts/build-vs2017-cmake-clang.bat'
      env:
        SHARED: False
        BUILD_TYPE: Debug

- job: VS${{ parameters.visualstudio }}MSVC
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    configuration: debug
    platform: x64
  steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: systeminfo;
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: git submodule update --init --recursive;
    - task: msbuild@1
      inputs:
        solution: ${{ parameters.solution }}
