#
# Author: github.com/luncliff (luncliff@gmail.com)
#
# References
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#passing-parameters
#

jobs:
- job: VS${{ parameters.visualstudio }}Clang
  pool:
    vmImage: 'windows-2019'
  steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: git submodule update --init --recursive;
    - task: ChocolateyCommand@0
      inputs:
        command: 'install'
        installPackageId: 'ninja'
        installInstallArgs: '--no-progress --yes'
    - task: ChocolateyCommand@0
      inputs:
        command: 'install'
        installPackageId: 'llvm'
        installInstallArgs: '--no-progress --yes'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          $env:PATH="C:\Program Files\LLVM\bin;$env:PATH";
          clang-cl --version;
    # - task: BatchScript@1
    #   inputs:
    #     filename: './scripts/build-vs2019-cmake-clang.bat'
    - task: CmdLine@2
      inputs:
        script: |
          setx path "%PATH%;C:\Program Files\LLVM\bin;";
          clang-cl --version;
          call ./scripts/build-vs2019-cmake-clang.bat;
      env:
        SHARED: False
        BUILD_TYPE: Debug

- job: VS${{ parameters.visualstudio }}MSVC
  pool:
    vmImage: 'windows-2019'
  variables:
    configuration: debug
    platform: x64
  steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: systeminfo;
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: git submodule update --init --recursive;
    - task: msbuild@1
      inputs:
        solution: ${{ parameters.solution }}
