# ---------------------------------------------------------------------------
#
#   Author
#     - luncliff@gmail.com
#   Reference
#     - https://docs.travis-ci.com/user/languages/cpp/
#     - https://libcxx.llvm.org/docs/BuildingLibcxx.html
#     - http://rkh.github.io/travis-encrypt/public/index.html
#     - https://blog.kowalczyk.info/article/k/how-to-install-latest-clang-6.0-on-ubuntu-16.04-xenial-wsl.html
#
# ---------------------------------------------------------------------------
sudo: false

git:
  submodules: false
  depth: 1
  
notifications:
  email:
    - luncliff@gmail.com

language: cpp

matrix: 
  include:
    # Linux : x86_64 Debug Dynamic
    - os: linux
      compiler: clang
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - llvm-6.0
            - llvm-6.0-tools
            - clang-6.0
            - libc++1
            - libc++-dev
            - libc++abi1
            - libc++abi-dev
            - ninja-build
            - tree
      env:
        - PLATFORM=linux
        - CONFIG=Debug
        - BUILD_SHARED=true
      before_install:
        - uname;
        - echo $TRAVIS_OS_NAME;
      install:
        - sudo bash ./scripts/install-libc++.sh 
      before_script:
        - cd ${TRAVIS_BUILD_DIR}
        - mkdir -p build && pushd build; # Create & Move to build directory
      script:
        - cmake ../ 
          -G "Ninja" 
          -DBUILD_SHARED_LIBS=$BUILD_SHARED 
          -DCMAKE_BUILD_TYPE=$CONFIG
          -DCMAKE_INSTALL_PREFIX=../install
        - ninja install
        # run tests
        - ./coroutine_test --reporter compact 
      after_success:
        - ldd ./libcoroutine.so
        # - tree -f ./CMakeFiles/
        # Get .gcda to extract .gcov
        - cp ./CMakeFiles/coroutine_test.dir/test/test.entry.cpp.* ./ ;
        # Generate .gcov files
        - llvm-cov-6.0 gcov -abcf ./test.entry.cpp.gcda > log-llvm-cov.txt
        - popd;
        - tree ./install

    # OS X : x86_64 Debug Dynamic
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      addons:
        homebrew:
          update: true
          packages:
            - ninja
            - tree
            - llvm
      env:
        - PLATFORM=osx
        - CONFIG=Debug
        - BUILD_SHARED=true
      before_install:
        - uname;
        - echo $TRAVIS_OS_NAME;
      install:
        - brew info llvm; # Check llvm version
      before_script:
        - cd ${TRAVIS_BUILD_DIR}
        - mkdir -p build && pushd build; # Create & Move to build directory
      script:
        - cmake ../ 
          -G "Ninja" 
          -DBUILD_SHARED_LIBS=$BUILD_SHARED 
          -DCMAKE_BUILD_TYPE=$CONFIG
          -DCMAKE_INSTALL_PREFIX=../install
        - ninja install
        # Display build results and start tests
        - ./coroutine_test
      after_success:
        - otool -L ./libcoroutine.dylib
        # - tree -f ./CMakeFiles/
        # MacOS: Run coverage tool for Debug build
        - cp ./CMakeFiles/coroutine_test.dir/test/test.entry.cpp.* ./ ;
        - gcov -abcf ./test.entry.cpp.gcda > log-gcov.txt;
        - ls -al | grep .gcov;
        - lcov --directory . --gcov-tool gcov --capture -o cov.info ;
        - genhtml cov.info -o cov_report;
        - tree ./cov_report;
        # Display build results
        - popd;
        - tree ./install
