# ---------------------------------------------------------------------------
#
#   Author
#     - luncliff@gmail.com
#   Reference
#     - https://docs.travis-ci.com/user/languages/cpp/
#     - https://libcxx.llvm.org/docs/BuildingLibcxx.html
#
# ---------------------------------------------------------------------------
sudo: false

git:
  submodules: false # - git submodule update --init --recursive
  depth: 1
  
branches:
  except:
  - gh-pages

language: cpp
compiler: clang

before_install:
  - uname;
  - echo $TRAVIS_OS_NAME;

install:
  # Download llvm/libc++ via Github submodule
  #   This is a little bit slower than svn
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then 
      git submodule update --init llvm libcxx libcxxabi;
    fi
  # - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then 
  #     svn co http://llvm.org/svn/llvm-project/llvm/trunk llvm > /dev/null;
  #     pushd llvm; svn log -l 1; popd;
  #     svn co http://llvm.org/svn/llvm-project/libcxx/trunk libcxx > /dev/null;
  #     pushd libcxx; svn log -l 1; popd;
  #     svn co http://llvm.org/svn/llvm-project/libcxxabi/trunk libcxxabi > /dev/null;
  #     pushd libcxxabi; svn log -l 1; popd;
  #   fi
  # Linux: Build libcxx
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then 
      mkdir -p prebuilt && pushd prebuilt;
      cmake ../libcxx -DLLVM_PATH=../llvm -DLIBCXX_CXX_ABI=libcxxabi -DLIBCXX_CXX_ABI_INCLUDE_PATHS=../libcxxabi/include -DCMAKE_INSTALL_PREFIX=. -DCMAKE_BUILD_TYPE=Release ;
      make -j10 install;
      rm CMakeCache.txt;
      tree ./include;
      popd;
    fi
  # Linux: Build libcxxabi
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then 
      mkdir -p prebuilt && pushd prebuilt;
      cmake ../libcxxabi -DLLVM_PATH=../llvm/ -DLIBCXXABI_LIBCXX_PATH=../libcxx/ -DCMAKE_INSTALL_PREFIX=../prebuilt/ ;
      make -j10 install;
      rm CMakeCache.txt;
      tree ./lib;
      popd;
    fi
  # MacOS: Upgrade llvm
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then 
      brew install tree ninja > /dev/null 2>&1; 
      brew upgrade llvm > /dev/null 2>&1;
      brew info llvm;
    fi
  - tree --version
  - ninja --version

before_script:
  # Create & Go to build directory
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p build && pushd build && pwd

script:
  - cmake ../ 
    -G "Ninja" 
    -DBUILD_SHARED_LIBS=$BUILD_SHARED 
    -DCMAKE_BUILD_TYPE=$CONFIG
    -DCMAKE_INSTALL_PREFIX=../$PLATFORM/$CONFIG
  - ninja -v install
  # Display build results and start tests
  - ./cppmagic_test
  - tree -f ./CMakeFiles/

after_success:
  - popd;
  - cd ${TRAVIS_BUILD_DIR}
  - tree $PLATFORM/$CONFIG

# Shared environment
# Default is ubuntu trusty
os: linux
dist: trusty
addons:
  apt:
    sources:
    - llvm-toolchain-trusty-5.0
    packages:
    - subversion
    - clang-5.0
    - libc++1
    - libc++-dev
    - libc++abi1
    - libc++abi-dev
    - ninja-build
    - tree

matrix: 
  include:
    # Linux : x86_64 Debug Dynamic
    - env:
      - PLATFORM=linux
      - CONFIG=Debug
      - BUILD_SHARED=true   
    # Linux : x86_64 Release Dynamic
    - env:
      - PLATFORM=linux
      - CONFIG=Release
      - BUILD_SHARED=true
  
    # OS X : x86_64 Debug Dynamic
    - os: osx
      osx_image: xcode9.3
      env:
        - PLATFORM=osx
        - CONFIG=Debug
        - BUILD_SHARED=true  
    # OS X : x86_64 Release Dynamic
    - os: osx
      osx_image: xcode9.3
      env:
        - PLATFORM=osx
        - CONFIG=Release
        - BUILD_SHARED=true

    # Android JNI: armeabi-v7a
    - language: android
      android:
      components:
        - tools
        - platform-tools
        - android-21
        - sys-img-armeabi-v7a-android-21
      env:
        - MAJOR_ABI=armeabi-v7a
      before_install:
        - sudo apt-get install wget unzip tree
      install:
        # Install submodules
        # - git submodule update --init llvm libcxx libcxxabi;
        # Accept SDK Licenses + Install NDK
        - yes | sdkmanager --update > /dev/null 2>&1
        - sdkmanager ndk-bundle > /dev/null 2>&1
        # Download/Install Gradle 
        - wget https://services.gradle.org/distributions/gradle-4.4-bin.zip
        - mkdir -p gradle
        - unzip -q -d ./gradle gradle-4.4-bin.zip
        - export GRADLE=gradle/gradle-4.4/bin/gradle
      before_script:
        - bash $GRADLE --version
      script:
        - bash $GRADLE clean assemble
notifications:
  email:
    - luncliff@gmail.com
