# ---------------------------------------------------------------------------
#
#   Author
#     - luncliff@gmail.com
#   Reference
#     - https://docs.travis-ci.com/user/languages/cpp/
#     - https://libcxx.llvm.org/docs/BuildingLibcxx.html
#
# ---------------------------------------------------------------------------
sudo: false

git:
  submodules: false
  depth: 1
  
branches:
  except:
  - gh-pages

language: cpp
compiler: clang

before_install:
  - uname;
  - echo $TRAVIS_OS_NAME;

install:
  # - git submodule update --init --recursive
  # - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then 
  #     svn co http://llvm.org/svn/llvm-project/llvm/trunk llvm > /dev/null;
  #     pushd llvm; svn log -l 1; popd;
  #     svn co http://llvm.org/svn/llvm-project/libcxx/trunk libcxx > /dev/null;
  #     pushd libcxx; svn log -l 1; popd;
  #     svn co http://llvm.org/svn/llvm-project/libcxxabi/trunk libcxxabi > /dev/null;
  #     pushd libcxxabi; svn log -l 1; popd;
  #   fi
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then 
      git submodule update --init llvm libcxx libcxxabi;
    fi
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then 
      mkdir -p prebuilt && pushd prebuilt;
      cmake ../libcxx -DLLVM_PATH=../llvm \
        -DLIBCXX_CXX_ABI=libcxxabi \
        -DLIBCXX_CXX_ABI_INCLUDE_PATHS=../libcxxabi/include \
        -DCMAKE_INSTALL_PREFIX=. \
        -DLIBCXX_ENABLE_SHARED=YES \
        -DCMAKE_BUILD_TYPE=Release ;
      make -j10 install;
      nm ./lib/libc++.so.1 | grep _cxa;
      nm --defined-only ./lib/libc++.so.1 | grep _cxa ;
      popd;
    fi
  # OSX: Upgrade llvm
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then 
      brew install tree ninja > /dev/null 2>&1; 
      brew upgrade llvm > /dev/null 2>&1;
      brew info llvm;
    fi
  # # Linux: Install llvm stable
  # # https://apt.llvm.org/
  # - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then 
  #     deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main;
  #     deb-src http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main;
  #     wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -;
  #     sudo apt-get install libllvm6.0 llvm-6.0 llvm-6.0-dev llvm-6.0-runtime; 
  #     sudo apt-get install clang-6.0 lldb-6.0 lld-6.0;
  #   fi
  - tree --version
  - ninja --version

before_script:
  # Create & Go to build directory
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p build && pushd build && pwd

script:
  - cmake ../ 
    -G "Ninja" 
    -DBUILD_SHARED_LIBS=$BUILD_SHARED 
    -DCMAKE_BUILD_TYPE=$CONFIG
    -DCMAKE_INSTALL_PREFIX=../$PLATFORM/$CONFIG
  - ninja install
  # Display build results and start tests
  - ./cppmagic_test
  - tree -f ./CMakeFiles/

after_success:
  - popd;
  - cd ${TRAVIS_BUILD_DIR}
  - tree $PLATFORM/$CONFIG

# Shared environment
# Default is ubuntu trusty
os: linux
dist: trusty
addons:
  apt:
    sources:
    - llvm-toolchain-trusty-5.0
    packages:
    - subversion
    - clang-5.0
    - libc++-1
    - libc++-dev
    - libc++abi1
    - libc++abi-dev
    - ninja-build
    - tree

matrix: 
  include:
    # Linux : x86_64 Debug Static
    - env:
      - PLATFORM=linux
      - CONFIG=Debug
      - BUILD_SHARED=false 
    # Linux : x86_64 Debug Dynamic
    - env:
      - PLATFORM=linux
      - CONFIG=Debug
      - BUILD_SHARED=true 
  
    # # Linux : x86_64 Release Static
    # - env:
    #   - PLATFORM=linux
    #   - CONFIG=Release
    #   - BUILD_SHARED=false
    # # Linux : x86_64 Release Dynamic
    # - env:
    #   - PLATFORM=linux
    #   - CONFIG=Release
    #   - BUILD_SHARED=true
  
    # OS X : x86_64 Debug Static
    - os: osx
      osx_image: xcode9.3
      env:
        - PLATFORM=osx
        - CONFIG=Debug
        - BUILD_SHARED=false
    # OS X : x86_64 Debug Dynamic
    - os: osx
      osx_image: xcode9.3
      env:
        - PLATFORM=osx
        - CONFIG=Debug
        - BUILD_SHARED=true
  
    # # OS X : x86_64 Release Static
    # - os: osx
    #   osx_image: xcode9.3
    #   env:
    #     - PLATFORM=osx
    #     - CONFIG=Release
    #     - BUILD_SHARED=false
    # # OS X : x86_64 Release Dynamic
    # - os: osx
    #   osx_image: xcode9.3
    #   env:
    #     - PLATFORM=osx
    #     - CONFIG=Release
    #     - BUILD_SHARED=true

notifications:
  email:
    - luncliff@gmail.com
