# ---------------------------------------------------------------------------
#
#   Author
#     - luncliff@gmail.com
#   Reference
#     - https://docs.travis-ci.com/user/languages/cpp/
#     - https://libcxx.llvm.org/docs/BuildingLibcxx.html
#     - http://rkh.github.io/travis-encrypt/public/index.html
#     - https://blog.kowalczyk.info/article/k/how-to-install-latest-clang-6.0-on-ubuntu-16.04-xenial-wsl.html
#
# ---------------------------------------------------------------------------
sudo: false

git:
  submodules: true
  depth: 1
  
notifications:
  email:
    - luncliff@gmail.com

language: cpp

install:
  - cd ${TRAVIS_BUILD_DIR}
before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p build && pushd build;
script:
  - cmake ../ 
      -G "Ninja" 
      -DBUILD_SHARED_LIBS=$BUILD_SHARED 
      -DCMAKE_BUILD_TYPE=$CONFIG
      -DCMAKE_INSTALL_PREFIX=../install
  - ninja install
  # - ./test/coroutine_test
  - ./test/coroutine_test [thread]
  - ./test/coroutine_test [generic]
  - ./test/coroutine_test [messaging]

matrix: 
  include:
    # OS X : x86_64 Debug Dynamic
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      addons:
        homebrew:
          # update: true
          packages:
            - ninja
            - tree
      env:
        - PLATFORM=osx
        - CONFIG=Debug
        - BUILD_SHARED=true
      before_install:
        - uname;
        - echo $TRAVIS_OS_NAME;
        - brew info llvm;
      after_success:
        - otool -L ./modules/libcoroutine.dylib
        - popd;
        - tree ./install

    # OS X : x86_64 Release Dynamic
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      addons:
        homebrew:
          # update: true
          packages:
            - ninja
            - tree
      env:
        - PLATFORM=osx
        - CONFIG=Release
        - BUILD_SHARED=true
      before_install:
        - uname;
        - echo $TRAVIS_OS_NAME;
        - brew info llvm;
      after_success:
        - otool -L ./modules/libcoroutine.dylib
        - popd;
        - tree ./install

    # Linux : x86_64 Debug Dynamic
    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-6.0
          packages:
            - libc++-dev
            - libc++abi-dev
            - ninja-build
            - tree
            - cmake
      env:
        - PLATFORM=linux
        - CONFIG=Debug
        - BUILD_SHARED=true
      before_install:
        - uname;
        - echo $TRAVIS_OS_NAME;
      after_success:
        - ldd ./modules/libcoroutine.so
        - popd;
        - tree ./install

    # Linux : x86_64 Release Dynamic
    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-6.0
          packages:
            - libc++-dev
            - libc++abi-dev
            - ninja-build
            - tree
            - cmake
      env:
        - PLATFORM=linux
        - CONFIG=Release
        - BUILD_SHARED=true
      before_install:
        - uname;
        - echo $TRAVIS_OS_NAME;
      after_success:
        - ldd ./modules/libcoroutine.so
        - popd;
        - tree ./install
