#
#   Author
#     - luncliff@gmail.com
#

git:
  submodules: true
  quiet: true
  depth: 5

branches:
  except:
    - docs
    - skip/*

notifications:
  email:
    - luncliff@gmail.com

addons:
  homebrew:
    packages:
      # - llvm # already installed
      - cmake
      - tree

  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-6.0
      - llvm-toolchain-xenial-7
      - llvm-toolchain-xenial-8
    packages:
      - g++-9
      - clang-6.0
      - clang-7
      - clang-8
      - libc++abi-8-dev
      - tree
      - wget
      - tar
      - rsync

language: cpp

install:
  # for this env, we don't have to use setup-compilers script
  # since we already installed them
  - if [ ${TRAVIS_OS_NAME} == "linux" ]; then
    sudo rm -rf /usr/local/clang-7.0.0;
    sudo rm -rf /usr/local/cmake-3.12.4;
    sudo bash ./scripts/install-cmake-3.sh;
    export CC=gcc-9 CXX=g++-9;
    sudo bash ./scripts/install-libcxx.sh release_90;
    fi
  - if [ ${TRAVIS_OS_NAME} == "osx" ]; then
    brew info llvm;
    fi

before_script:
  - if [ ${TRAVIS_OS_NAME} == "linux" ]; then
    export CC=${TRAVIS_COMPILER};
    export CXX=${TRAVIS_COMPILER};
    fi
  - if [ ${TRAVIS_OS_NAME} == "osx" ]; then
    export CXX=${TRAVIS_COMPILER};
    fi

script:
  - cmake .
    -D CMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/install
    -D BUILD_SHARED_LIBS=${SHARED}
    -D CMAKE_BUILD_TYPE=${BUILD_TYPE}
    -D USE_PORTABLE_HEADER=${PORTABLE}
  - cmake --build . --config ${BUILD_TYPE}
  - cmake --build . --target install
  - ctest --output-on-failure

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - tree ./install

jobs:
  include:
    - os: osx
      osx_image: xcode10.3
      compiler: clang
      env:
        - BUILD_TYPE=Debug    SHARED=True  PORTABLE=True
    - os: osx
      osx_image: xcode10.3
      compiler: clang
      env:
        - BUILD_TYPE=Debug    SHARED=False PORTABLE=True

    - os: osx
      osx_image: xcode11
      compiler: clang
      env:
        - BUILD_TYPE=Debug    SHARED=True  PORTABLE=True
    - os: osx
      osx_image: xcode11
      compiler: clang
      env:
        - BUILD_TYPE=Debug    SHARED=False PORTABLE=True

    - os: linux
      dist: xenial
      compiler: clang-6.0
      env:
        - BUILD_TYPE=Debug    SHARED=True  PORTABLE=True
    - os: linux
      dist: xenial
      compiler: clang-6.0
      env:
        - BUILD_TYPE=Debug    SHARED=False PORTABLE=True

    - os: linux
      dist: xenial
      compiler: clang-7
      env:
        - BUILD_TYPE=Debug    SHARED=True  PORTABLE=True
    - os: linux
      dist: xenial
      compiler: clang-7
      env:
        - BUILD_TYPE=Debug    SHARED=False PORTABLE=True

    - os: linux
      dist: xenial
      compiler: clang-8
      env:
        - BUILD_TYPE=Debug    SHARED=True  PORTABLE=True
    - os: linux
      dist: xenial
      compiler: clang-8
      env:
        - BUILD_TYPE=Debug    SHARED=False PORTABLE=True
