sudo: false

git:
  submodules: false
  depth: 1
  
branches:
  except:
  - gh-pages

language: cpp
compiler: clang

before_install:
  - uname;
  - echo $TRAVIS_OS_NAME;
  # Use brew for OSX image
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then 
      brew install tree ninja > /dev/null 2>&1; 
      brew upgrade llvm > /dev/null 2>&1;
      brew info llvm;
    fi
  - tree --version
  - ninja --version

# install:
#   - git submodule update --init --recursive

before_script:
  # Go to build directory
  - mkdir -p build && cd build && pwd

script:
  - cmake ../ 
    -G "Ninja" 
    -DBUILD_SHARED_LIBS=$BUILD_SHARED 
    -DCMAKE_BUILD_TYPE=$CONFIG
  - ninja install
  - tree .
  - ./cppmagic_test

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - tree ./install

# Shared environment
# Default is ubuntu trusty
os: linux
dist: trusty
addons:
  apt:
    sources:
    - llvm-toolchain-trusty-5.0
    packages:
    - clang-5.0
    - libc++-dev  
    - ninja-build
    - tree

matrix: 
  include:
    # # Linux : x86_64 Debug Static
    # - env:
    #   - PLATFORM=linux
    #   - CONFIG=Debug
    #   - BUILD_SHARED=false 
    # # Linux : x86_64 Debug Dynamic
    # - env:
    #   - PLATFORM=linux
    #   - CONFIG=Debug
    #   - BUILD_SHARED=true 
  
    # # Linux : x86_64 Release Static
    # - env:
    #   - PLATFORM=linux
    #   - CONFIG=Release
    #   - BUILD_SHARED=false
    # # Linux : x86_64 Release Dynamic
    # - env:
    #   - PLATFORM=linux
    #   - CONFIG=Release
    #   - BUILD_SHARED=true
  
    # OS X : x86_64 Debug Static
    - os: osx
      osx_image: xcode9.3
      env:
        - PLATFORM=osx
        - CONFIG=Debug
        - BUILD_SHARED=false
    # OS X : x86_64 Debug Dynamic
    - os: osx
      osx_image: xcode9.3
      env:
        - PLATFORM=osx
        - CONFIG=Debug
        - BUILD_SHARED=true
  
    # OS X : x86_64 Release Static
    - os: osx
      osx_image: xcode9.3
      env:
        - PLATFORM=osx
        - CONFIG=Release
        - BUILD_SHARED=false
    # OS X : x86_64 Release Dynamic
    - os: osx
      osx_image: xcode9.3
      env:
        - PLATFORM=osx
        - CONFIG=Release
        - BUILD_SHARED=true

notifications:
  email:
    - luncliff@gmail.com
