#
#   Author
#     - luncliff@gmail.com
#
sudo: false

git:
  submodules: true
  depth: 5

branches:
  except:
    - docs

notifications:
  email:
    - luncliff@gmail.com

os: linux
dist: xenial
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-7
      - llvm-toolchain-xenial-8
    packages:
      - g++-7
      - g++-8
      - libc++-7-dev
      - libc++abi-7-dev
      - unzip
      - curl
      - ninja-build
      - tree
      - jq

services:
  - docker

matrix:
  include:
    - name: GCC-10 Info (Coroutine Branch)
      before_install:
        - docker info
      install:
        - docker pull luncliff/gcc
        - docker inspect luncliff/gcc | jq
      script:
        - docker run --rm luncliff/gcc gcc-10 --version

    - name: Build/Test with Docker Container
      install:
        - docker pull luncliff/gcc
        - docker run -it -d --name gcc_10_builder -w /code/build -v $(pwd):/code luncliff/gcc
      before_script:
        - export RUN="docker exec gcc_10_builder"
        - $RUN apt install -y -qq cmake rsync wget tar unzip
        - $RUN cmake --version
      script:
        - $RUN cmake .. -DCMAKE_CXX_COMPILER=gcc-10
        - $RUN cmake --build .
        - $RUN ctest --output-on-failure
