#
#   Author
#     - luncliff@gmail.com
#
sudo: false

git:
  submodules: true
  depth: 5

branches:
  except:
    - docs

notifications:
  email:
    - luncliff@gmail.com

os: linux
dist: xenial
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - curl

services:
  - docker

matrix:
  include:
    - name: GCC branch for C++ Coroutine
      before_install:
        - docker info
      install:
        - docker pull luncliff/gcc
      script:
        - docker run --rm luncliff/gcc gcc-10 --version
        - docker build --file ./build.docker . -t luncliff/coroutine
