# ---------------------------------------------------------------------------
#
#   Author
#     - luncliff@gmail.com
#   Reference
#     - https://docs.travis-ci.com/user/languages/cpp/
#     - https://libcxx.llvm.org/docs/BuildingLibcxx.html
#     - http://rkh.github.io/travis-encrypt/public/index.html
#     - https://blog.kowalczyk.info/article/k/how-to-install-latest-clang-6.0-on-ubuntu-16.04-xenial-wsl.html
#
# ---------------------------------------------------------------------------
sudo: false

git:
  submodules: true
  depth: 1
  
notifications:
  email:
    - luncliff@gmail.com

language: cpp

before_install:
  - uname -a
install:
  - echo ${TRAVIS_OS_NAME};
  - if [ ${TRAVIS_OS_NAME} == "linux" ]; then
      sudo bash ./scripts/install-libc++.sh;
      sudo rm -rf prebuilt;
    fi
  - if [ ${TRAVIS_OS_NAME} == "osx" ]; then
      brew info llvm;
    fi
before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p build && pushd build;
script:
  - cmake ../ 
      -G "Ninja" 
      -DBUILD_SHARED_LIBS=$BUILD_SHARED 
      -DCMAKE_BUILD_TYPE=$CONFIG
      -DCMAKE_INSTALL_PREFIX=../install
  - ninja install
  - ./test/coroutine_test [thread]
  - ./test/coroutine_test [generic]
  - ./test/coroutine_test [messaging]
  - ./test/coroutine_test

matrix: 
  include:
    # OS X : x86_64 Debug Dynamic
    - os: osx
      osx_image: xcode10.1
      compiler: clang
      addons:
        homebrew:
          packages:
            - ninja
            - tree
      env:
        - PLATFORM=osx
        - CONFIG=Debug
        - BUILD_SHARED=true
      after_success:
        - otool -L ./modules/libcoroutine.dylib
        - popd;
        - tree ./install

    # OS X : x86_64 Release Dynamic
    - os: osx
      osx_image: xcode10.1
      compiler: clang
      addons:
        homebrew:
          packages:
            - ninja
            - tree
      env:
        - PLATFORM=osx
        - CONFIG=Release
        - BUILD_SHARED=true
      after_success:
        - otool -L ./modules/libcoroutine.dylib
        - popd
        - tree ./install

    # OS X : x86_64 Debug Static
    - os: osx
      osx_image: xcode10.1
      compiler: clang
      addons:
        homebrew:
          packages:
            - ninja
            - tree
      env:
        - PLATFORM=osx
        - CONFIG=Debug
        - BUILD_SHARED=false
      after_success:
        - file ./modules/libcoroutine.a
        - otool -L ./modules/libcoroutine.a
        - popd
        - tree ./install

    # OS X : x86_64 Release Static
    - os: osx
      osx_image: xcode10.1
      compiler: clang
      addons:
        homebrew:
          packages:
            - ninja
            - tree
      env:
        - PLATFORM=osx
        - CONFIG=Release
        - BUILD_SHARED=false
      after_success:
        - file ./modules/libcoroutine.a
        - otool -L ./modules/libcoroutine.a
        - popd
        - tree ./install

    # OS X : iPhone OS Release
    - os: osx
      osx_image: xcode10.1
      compiler: clang
      addons:
        homebrew:
          packages:
            - ninja
            - tree
      env:
        - PLATFORM=ios
        - CONFIG=Release
        - BUILD_SHARED=true
      script:
        - cmake ../ 
            -DBUILD_SHARED_LIBS=$BUILD_SHARED 
            -DCMAKE_BUILD_TYPE=$CONFIG
            -DCMAKE_INSTALL_PREFIX=../install
            -DCMAKE_TOOLCHAIN_FILE=../external/ios-cmake/ios.toolchain.cmake
            -DENABLE_BITCODE=false
            -DIOS_DEPLOYMENT_TARGET=10.13
        - make install
      after_success:
        - file ./modules/libcoroutine.dylib
        - otool -L ./modules/libcoroutine.dylib
        - popd
        - tree ./install
