#
#   Author
#     - luncliff@gmail.com
#   Reference
#     - https://www.appveyor.com/docs/appveyor-yml/
#     - https://github.com/appveyor/ci/issues/899#issuecomment-230360978
#     - https://www.appveyor.com/docs/lang/cpp/
#
version: 1.4.{build}

branches:
  except:
    - docs

clone_script:  
  - ps: git clone -q --recursive --branch $env:APPVEYOR_REPO_BRANCH https://github.com/$env:APPVEYOR_REPO_NAME.git $env:APPVEYOR_BUILD_FOLDER

notifications:
  - provider: Email
    to:
      - luncliff@gmail.com

image:
  - Visual Studio 2017

platform:
  - x64

configuration:
  - Debug
  - Release

environment:
  matrix:
    - compiler: msvc
    - compiler: clang-cl

matrix:
  allow_failures:
    - image: Visual Studio 2017
      compiler: clang-cl

for:
  - matrix:
      only:
        - image: Visual Studio 2017
          compiler: msvc
    build:
      parallel: true
      project: coroutine.sln
      verbosity: quiet
    before_test:
      - ps: $outdir=Join-Path -Path (pwd)   -ChildPath $env:PLATFORM
      - ps: $outdir=Join-Path -Path $outdir -ChildPath $env:CONFIGURATION
      - ps: Write-Host $outdir
    test_script:
      - ps: vstest.console "$outdir\coroutine_vstest_channel.dll"
      - ps: vstest.console "$outdir\coroutine_vstest_concrt.dll"
      - ps: vstest.console "$outdir\coroutine_vstest_network.dll"
      - ps: vstest.console "$outdir\coroutine_vstest_return.dll"
      - ps: vstest.console "$outdir\coroutine_vstest_yield.dll"

  - matrix:
      only:
        - image: Visual Studio 2017
          compiler: clang-cl
    install:
      # - ps: choco install --yes --no-progress --force cmake
      - ps: choco install --yes --no-progress ninja
      - ps: choco info llvm # LLVM is already installed
    before_build:
      - ps: cmake     --version
      - ps: clang-cl  --version
      - ps: New-Item -Name build -ItemType Directory
      - ps: Push-Location -Path build
    build_script:
      # emulate: Visual Studio Native Tools Command Prompt
      # https://www.appveyor.com/docs/lang/cpp/#visual-studio
      - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
      # ps: $env:CXX="clang-cl"
      - cmd: set CXX=clang-cl
      # for cmake, "-DCMAKE_CXX_COMPILER=clang-cl" can be ok
      - cmd: cmake .. -G Ninja -DUSE_CUSTOM_HEADER=true -DBUILD_SHARED_LIBS=false -DCMAKE_BUILD_TYPE=%configuration% -DCMAKE_INSTALL_PREFIX=../install/%platform%/%configuration%
      - cmd: cmake --build .
      - cmd: cmake --build . --target install
    after_build:
      - ps: Pop-Location
    before_test:
      - ps: Push-Location -Path build
    test_script:
      - ps: ctest --output-on-failure
