# ---------------------------------------------------------------------------
#
#   Author
#     - luncliff@gmail.com
#   Reference
#     - https://www.appveyor.com/docs/appveyor-yml/
#
# ---------------------------------------------------------------------------
version: 1.3.{build}

clone_script:
  # https://github.com/appveyor/ci/issues/899#issuecomment-230360978
 - ps: git clone -q --recursive --branch $env:APPVEYOR_REPO_BRANCH https://github.com/$env:APPVEYOR_REPO_NAME.git $env:APPVEYOR_BUILD_FOLDER
 - ps: git checkout -qf $env:APPVEYOR_REPO_COMMIT

notifications:
  - provider: Email
    to:
      - luncliff@gmail.com

image:
  - Visual Studio 2017
  - Ubuntu1804

platform:
  - x64

configuration:
  - Debug
  - Release

environment:
  matrix:
    - compiler: msvc
    - compiler: clang

matrix:
  exclude:
    - image: Ubuntu1804
      compiler: msvc
  allow_failures:
    - image: Visual Studio 2017
      compiler: clang
    - image: Ubuntu1804

for:
# MSVC: use Visual Studio solution file
-
  matrix:
    only:
      - image: Visual Studio 2017
        compiler: msvc
  install:
    - ps: Write-Host $env:PLATFORM $env:CONFIGURATION $env:APPVEYOR_BUILD_FOLDER 
  build:
    parallel: true
    project: coroutine.sln
    verbosity: quiet
  after_build:
    # Rename the variable for build output
    - ps: if( $env:PLATFORM -eq "x86" ){ $env:PLATFORM="Win32"; }
    - ps: tree /F ./$env:PLATFORM
  before_test:
    - ps: $TestDLL= "$env:APPVEYOR_BUILD_FOLDER/$env:PLATFORM/$env:CONFIGURATION/coroutine_vstest.dll"
  test_script:
    - ps: vstest.console.exe $TestDLL /Tests:generator
    - ps: vstest.console.exe $TestDLL /Tests:unplug
    - ps: vstest.console.exe $TestDLL /Tests:channel
    - ps: vstest.console.exe $TestDLL /Tests:wait_group

# clang-cl: use CMake + Ninja + Clang
# The build step expects cmdlet environment...
-
  matrix:
    only:
      - image: Visual Studio 2017
        compiler: clang
  install:
    - ps: Write-Host $env:APPVEYOR_BUILD_FOLDER
    - ps: choco install ninja   # Download Ninja with chocolaty package manager
    - ps: choco info    llvm    # LLVM is already installed. So just show the version info
    - ps: cmake --version
    - ps: ninja --version
    - ps: clang --version       # version: 6.0+
    - ps: clang-cl --version    # cl.exe for clang
    # Rename the variable for build output
    - ps: if( $env:PLATFORM -eq "x86" ){ $env:PLATFORM="Win32" }
  before_build:
    - ps: Write-Host $env:PLATFORM $env:CONFIGURATION
  build_script:
    - ps: New-Item -Name build -ItemType Directory
    - ps: Push-Location -Path build
    - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
    - cmd: set CXX=clang-cl # ps: $env:CXX = "clang-cl"
    # for cmake, this can be ok. -DCMAKE_CXX_COMPILER=clang-cl
    - cmd: cmake ../ -G Ninja -DBUILD_SHARED_LIBS=true -DCMAKE_BUILD_TYPE=%configuration% -DCMAKE_INSTALL_PREFIX=./%platform%/%configuration% 
    - cmd: ninja
  after_build:
    # copy dll for test executable
    - ps: Copy-Item ./modules/coroutine.dll ./test
    - ps: Pop-Location
  test_script:
    - ps: ./build/test/coroutine_test.exe [thread]
    - ps: ./build/test/coroutine_test.exe [generic]
    - ps: ./build/test/coroutine_test.exe [messaging]

# Linux clang: expect 6.0+ (the feature became available since 5.0)
-
  matrix:
    only:
      - image: Ubuntu1804
        compiler: clang
  install:
    - sh: uname -a
    # install utilities
    - sh: sudo apt update -y -qq
    - sh: sudo apt install -y -qq --fix-missing wget unzip ninja-build cmake gnupg2 tree
    # install GCC
    - sh: sudo apt install -y -qq --fix-missing gcc-7 g++-7 libc++abi-dev libc++-dev    
    # install LLVM toolchain
    # - sh: wget -O llvm.key https://apt.llvm.org/llvm-snapshot.gpg.key
    # - sh: sudo apt-key add ./llvm.key
    # - sh: sudo apt update -y
    - sh: sudo apt install -y --fix-missing clang-6.0 llvm-6.0 llvm-6.0-tools
    # report version    
    - sh: cmake --version
    - sh: ninja --version
    - sh: clang-6.0 --version
  before_build:
    - sh: pwd
    - sh: sudo bash ./scripts/install-libc++.sh
    - sh: sudo rm -rf ./prebuilt
    - sh: mkdir -p build && pushd build
  build_script:
    - sh: export CC=clang-6.0
    - sh: export CXX=clang-6.0
    - sh: echo "$CC $CXX"
    - sh: cmake ../ -G Ninja -DCMAKE_BUILD_TYPE=$CONFIGURATION -DCMAKE_INSTALL_PREFIX=./install
    - sh: ninja install
  after_build:
    - sh: popd
  test_script:
    # - ps: ./build/test/coroutine_test
    - ps: ./build/test/coroutine_test [messaging]
    - ps: ./build/test/coroutine_test [thread]
    - ps: ./build/test/coroutine_test [generic]
