version: 1.0.{build}

clone_depth: 1

image: 
  - Visual Studio 2017

platform: 
  - x86   # Win32
  - x64

configuration:
  - Debug
  - Release

environment:
  matrix:
    - compiler: clang

install:
  - ps: Write-Host $env:PLATFORM $env:CONFIGURATION $env:APPVEYOR_BUILD_FOLDER 
  
   # Build Tool: CMake + Ninja
  - choco install ninja
  - cmake --version
  - ninja --version
  
  # Compiler: clang-cl
  # - choco install llvm
  - clang --version
  - clang-cl -v
  # this setup is necessary
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64

before_build:
  - mkdir build && cd build/
  - set CC=clang-cl
  - set CXX=clang-cl
  - cmake ../ 
    -G Ninja 
    "-DCMAKE_BUILD_TYPE=%configuration%"
  
build_script:
  - ninja install

after_build:
  # Rename the variable for build output
  - ps: if( $env:PLATFORM -eq "x86" ){ $env:PLATFORM="Win32"; }
  - cd %APPVEYOR_BUILD_FOLDER% 

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

before_deploy:
  - ps: cd $env:APPVEYOR_BUILD_FOLDER
  
deploy:
  - provider: GitHub
    auth_token:
      secure: Wlp/6n2lRS4hsvUlZpGjcmDKufr5TfbB3WhUMiqbQvxTkgTL+RNWTtP8C198boyH
    prerelease: true
    # artifact: /.*\.nupkg/
    description: "Release: $(appveyor_build_version)"
    on:
      appveyor_repo_tag: true 
  # - provider: NuGet
  #   api_key:
  #     secure: WA47md7hTipdB62+gloqH00ycFx76g7txPn5ZbtqaD5K7jjSbTJKkWr8FkKBG4YK
  #   artifact: /.*\.nupkg/


after_deploy:
  - ps: cd $env:APPVEYOR_BUILD_FOLDER

notifications:
  - provider: Email
    to:
      - luncliff@gmail.com

