site_name: luncliff/coroutine

nav:
  - Home: Home.md
  - Articles:
    - Awaitable Event: Awaitable-event-using-coroutine,-epoll,-and-eventfd.md
  - frame.h:
    - coroutine_handle: frame.h-coroutine_handle.md
    - coroutine_traits: frame.h-coroutine_traits.md
    - suspend_types: frame.h-suspend_types.md
    - compiler: frame.h-compiler_specific.md
  - return.h:
    - frame: return.h-frame.md
    - no_return: return.h-no_return.md
  - channel.hpp:
    - Concept: channel.hpp-concept.md
    - Read and Write: channel.hpp-read_write.md
    - Select on multiple channel: channel.hpp-select.md
  - yield.hpp:
    - Generator: yield.hpp-enumerable.md
    - Async Generator: yield.hpp-sequence.md
  - concrt.h:
    - section: concrt.h-section.md
    - latch: concrt.h-latch.md

theme:
  name: material

markdown_extensions:
  - codehilite
