site_name: luncliff/coroutine
site_description: 'C++ 20 Coroutine in Action.'

repo_url: http://github.com/luncliff/coroutine
site_url: https://luncliff.github.io/coroutine/Home

theme:
  name: material

markdown_extensions:
  - codehilite

nav:
  - Home: Home.md

  - Articles:
    - PPT - C++ Korea 5th Seminar: ppt/Exploring-the-Cpp-Coroutine.md
    - Awaitable event using the coroutine, epoll and eventfd: articles/awaitable-event.md
    - Designing the coroutine channel: articles/designing-the-channel.md
    # - Example - await_transform: articles/example-of-await_transform.md
    # - Function that selects its thread: articles/thread-selecting-function.md
    # - Why this library doesn't support Task?: articles/why-no-coroutine-task-return.md

  - How To:
    - Import:
      - Visual Studio: import-using-visualstudio.md
      - CMake: import-using-cmake.md
    - Build:
      - Visual Studio: build-using-visualstudio.md
      - CMake: build-using-cmake.md
    - Start Your Project!: howto-start-yours.md

  - Features:
    - frame.h:
      - Overview: frame-overview.md
      - Compiler Specific Issues: frame-compiler_specific.md
      - coroutine_handle: frame-coroutine_handle.md
      - coroutine_traits: frame-coroutine_traits.md
      - Suspend Types: frame-suspend_types.md
    - return.h:
      - Overview: return-overview.md
      - no_return: return-no_return.md
      - frame: return-frame.md
    - yield.hpp:
      - Overview: yield-overview.md
      - Generator: yield-enumerable.md
      - Async Generator: yield-sequence.md
    - channel.hpp:
      - Overview: channel-overview.md
      - Read/Write: channel-read_write.md
      - Select on multiple channel: channel-select.md
    - concrt.h:
      - Overview: concrt-overview.md
      - section: concrt-section.md
      - latch: concrt-latch.md
      - Windows Thread Pool: concrt-ptp_work.md
      - Windows Event: concrt-ptp_event.md
      - POSIX event: articles/awaitable-event.md
    - net.h:
      - Overview: net-overview.md
      - Windows Socket 2: net-implementation-winsock2.md
      - Kqueue: net-implementation-kqueue.md
      - Epoll: net-implementation-epoll.md

